version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_nutripet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nutripetdb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

  backend:
    container_name: nutripet_backend
    build:
      context: ./backend/nutripet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: nutripet_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
    name: mongo_data_nutripet