server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:example@mongodb:27017/nutripetdb?authSource=admin
#      host: localhost
#      port: 27017
#      authentication-database: nutripetdb
#      username: root
#      password: example
